services:
  db:
    image: postgres:16
    container_name: spy_cats_db
    restart: always
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'pg_isready -U $DB_USER -d $DB_NAME'"]
      interval: 3s
      timeout: 3s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spy_cats_migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
    - ./internal/database/migrations:/migrations
    working_dir: /migrations
    entrypoint: /bin/sh -c
    command: >
      "goose postgres
      postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}
      up"

  app:
    build: .
    container_name: spy_cats_api
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    env_file: 
      - .env
    command: ["go", "run", "./cmd/server/main.go"]
    volumes:
      - .:/app
    working_dir: /app